### ISSUE TITLE
How to use this addon

### ISSUE THREAD

**Issue by jinyangcruise** [tangentstorm/godot-waveform#1]
I don't know how to use this addon, can you please add some instructions please?

**Comment by tangentstorm** [comment]
Hey @jinyangcruise ... It's still kind of a work in progress. Basically you put the code here in `addons/waveform` in your project.

To enable recording, you may also need to set the default bus layout and check the "audio input" button in the audio settings:

![image](https://user-images.githubusercontent.com/2150613/215990503-7ce97667-5997-4705-88a2-efa0eac5ff33.png)

Then enable the plugin under the plugins tab:

![image](https://user-images.githubusercontent.com/2150613/215990732-1ed54a99-f639-43ec-b24e-c65b5822a021.png)

Now you should see a panel called "waveform" in the bottom dock:

Click the white area, and hold the insert key to record audio from your microphone and you'll see the waveform:

![image](https://user-images.githubusercontent.com/2150613/215991500-c4b46b61-15fc-4364-81c3-3e3d2f5f5a9d.png)

You can highlight parts of it to clip, or save the new recording.

You can also click any *.wav file and it will open in the waveform tab.

The main branch of this repo is for godot 4. There's a godot 3 version in the [godot-3.5.1](https://github.com/tangentstorm/godot-waveform/tree/godot-3.5.1) tag

It's not a full featured audio editor, obviously. I just use it to record short clips as a component for another plugin, where I record one line of text at a time for my videos rather than editing an entire voiceover later:

https://github.com/tangentstorm/orgprez

Does that help? Let me know if I missed anything.

**Comment by jinyangcruise** [comment]
Thank you very much!
I was looking for some methods to draw waveform of an audio then I found your addon. It's very beautiful!
